// Seeded California neighborhood market data (2025-2026 estimates)
// Only market data — financing params come from user inputs at load time
window.CA_NEIGHBORHOODS = [
  // Bay Area
  {
    name: 'San Francisco - Sunset',
    region: 'Bay Area',
    medianPrice: 1350000,
    expectedRent: 4200,
    propertyTaxRate: 1.18,
    monthlyHOA: 0,
    annualInsurance: 4725,
    vacancyRate: 3,
    maintenanceRate: 1,
    managementFee: 0,
    appreciationRate: 3,
    currentRentIfBuying: 3500,
  },
  {
    name: 'San Jose - Willow Glen',
    region: 'Bay Area',
    medianPrice: 1500000,
    expectedRent: 4000,
    propertyTaxRate: 1.20,
    monthlyHOA: 0,
    annualInsurance: 5250,
    vacancyRate: 3,
    maintenanceRate: 1,
    managementFee: 0,
    appreciationRate: 3.5,
    currentRentIfBuying: 3800,
  },
  {
    name: 'Oakland - Temescal',
    region: 'Bay Area',
    medianPrice: 850000,
    expectedRent: 3200,
    propertyTaxRate: 1.30,
    monthlyHOA: 0,
    annualInsurance: 2975,
    vacancyRate: 4,
    maintenanceRate: 1,
    managementFee: 0,
    appreciationRate: 3,
    currentRentIfBuying: 2800,
  },
  // SoCal - Los Angeles
  {
    name: 'Los Angeles - Silver Lake',
    region: 'SoCal - LA',
    medianPrice: 1100000,
    expectedRent: 3500,
    propertyTaxRate: 1.16,
    monthlyHOA: 0,
    annualInsurance: 3850,
    vacancyRate: 4,
    maintenanceRate: 1,
    managementFee: 0,
    appreciationRate: 3,
    currentRentIfBuying: 3000,
  },
  {
    name: 'Los Angeles - Koreatown',
    region: 'SoCal - LA',
    medianPrice: 650000,
    expectedRent: 2600,
    propertyTaxRate: 1.16,
    monthlyHOA: 250,
    annualInsurance: 2275,
    vacancyRate: 4,
    maintenanceRate: 1,
    managementFee: 0,
    appreciationRate: 2.5,
    currentRentIfBuying: 2200,
  },
  {
    name: 'Long Beach - Belmont Shore',
    region: 'SoCal - LA',
    medianPrice: 950000,
    expectedRent: 3400,
    propertyTaxRate: 1.17,
    monthlyHOA: 0,
    annualInsurance: 3325,
    vacancyRate: 4,
    maintenanceRate: 1,
    managementFee: 0,
    appreciationRate: 3,
    currentRentIfBuying: 2800,
  },
  {
    name: 'Inglewood',
    region: 'SoCal - LA',
    medianPrice: 720000,
    expectedRent: 2800,
    propertyTaxRate: 1.19,
    monthlyHOA: 0,
    annualInsurance: 2520,
    vacancyRate: 5,
    maintenanceRate: 1,
    managementFee: 0,
    appreciationRate: 3,
    currentRentIfBuying: 2400,
  },
  // SoCal - Orange County
  {
    name: 'Irvine',
    region: 'SoCal - OC',
    medianPrice: 1200000,
    expectedRent: 3800,
    propertyTaxRate: 1.05,
    monthlyHOA: 350,
    annualInsurance: 4200,
    vacancyRate: 3,
    maintenanceRate: 1,
    managementFee: 0,
    appreciationRate: 3,
    currentRentIfBuying: 3200,
  },
  {
    name: 'Anaheim',
    region: 'SoCal - OC',
    medianPrice: 680000,
    expectedRent: 2700,
    propertyTaxRate: 1.08,
    monthlyHOA: 300,
    annualInsurance: 2380,
    vacancyRate: 5,
    maintenanceRate: 1,
    managementFee: 0,
    appreciationRate: 2.5,
    currentRentIfBuying: 2300,
  },
  {
    name: 'Santa Ana',
    region: 'SoCal - OC',
    medianPrice: 750000,
    expectedRent: 2900,
    propertyTaxRate: 1.10,
    monthlyHOA: 0,
    annualInsurance: 2625,
    vacancyRate: 5,
    maintenanceRate: 1,
    managementFee: 0,
    appreciationRate: 2.5,
    currentRentIfBuying: 2500,
  },
  // SoCal - San Diego
  {
    name: 'San Diego - North Park',
    region: 'SoCal - SD',
    medianPrice: 900000,
    expectedRent: 3200,
    propertyTaxRate: 1.13,
    monthlyHOA: 0,
    annualInsurance: 3150,
    vacancyRate: 4,
    maintenanceRate: 1,
    managementFee: 0,
    appreciationRate: 3,
    currentRentIfBuying: 2700,
  },
  {
    name: 'San Diego - Chula Vista',
    region: 'SoCal - SD',
    medianPrice: 720000,
    expectedRent: 2800,
    propertyTaxRate: 1.15,
    monthlyHOA: 100,
    annualInsurance: 2520,
    vacancyRate: 5,
    maintenanceRate: 1,
    managementFee: 0,
    appreciationRate: 3,
    currentRentIfBuying: 2400,
  },
  // Central Valley
  {
    name: 'Sacramento - Midtown',
    region: 'Central Valley',
    medianPrice: 520000,
    expectedRent: 2200,
    propertyTaxRate: 1.25,
    monthlyHOA: 0,
    annualInsurance: 1820,
    vacancyRate: 5,
    maintenanceRate: 1,
    managementFee: 0,
    appreciationRate: 3,
    currentRentIfBuying: 1900,
  },
  {
    name: 'Sacramento - Elk Grove',
    region: 'Central Valley',
    medianPrice: 580000,
    expectedRent: 2400,
    propertyTaxRate: 1.30,
    monthlyHOA: 50,
    annualInsurance: 2030,
    vacancyRate: 5,
    maintenanceRate: 1,
    managementFee: 0,
    appreciationRate: 3,
    currentRentIfBuying: 2000,
  },
  {
    name: 'Fresno',
    region: 'Central Valley',
    medianPrice: 380000,
    expectedRent: 1800,
    propertyTaxRate: 1.30,
    monthlyHOA: 0,
    annualInsurance: 1330,
    vacancyRate: 6,
    maintenanceRate: 1,
    managementFee: 0,
    appreciationRate: 2.5,
    currentRentIfBuying: 1500,
  },
  {
    name: 'Bakersfield',
    region: 'Central Valley',
    medianPrice: 340000,
    expectedRent: 1600,
    propertyTaxRate: 1.25,
    monthlyHOA: 0,
    annualInsurance: 1190,
    vacancyRate: 7,
    maintenanceRate: 1,
    managementFee: 0,
    appreciationRate: 2,
    currentRentIfBuying: 1400,
  },
  // Inland Empire
  {
    name: 'Riverside',
    region: 'Inland Empire',
    medianPrice: 550000,
    expectedRent: 2300,
    propertyTaxRate: 1.25,
    monthlyHOA: 0,
    annualInsurance: 1925,
    vacancyRate: 5,
    maintenanceRate: 1,
    managementFee: 0,
    appreciationRate: 3,
    currentRentIfBuying: 2000,
  },
  {
    name: 'San Bernardino',
    region: 'Inland Empire',
    medianPrice: 420000,
    expectedRent: 1900,
    propertyTaxRate: 1.28,
    monthlyHOA: 0,
    annualInsurance: 1470,
    vacancyRate: 6,
    maintenanceRate: 1,
    managementFee: 0,
    appreciationRate: 2.5,
    currentRentIfBuying: 1600,
  },
];
